# Generated by Django 4.1.1 on 2022-09-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registro',
            field=models.SmallIntegerField(unique=True),
        ),
    ]
