# Generated by Django 4.1.1 on 2022-09-11 19:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fechaNacimiento',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='persona',
            name='celular',
            field=models.BigIntegerField(default=0),
        ),
    ]
