# Generated by Django 4.1.1 on 2022-09-12 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_alter_doctor_persona_ptr_alter_doctor_registro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registro',
            field=models.SmallIntegerField(),
        ),
    ]
