# Generated by Django 4.1.1 on 2022-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_alter_doctor_registro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='registro',
            field=models.SmallIntegerField(default=0),
        ),
    ]
